version: 0.2

env:
  exported-variables:
    - CLOUDFRONT_DOMAIN

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - corepack enable && corepack install
      - npm install -g ts-node
      - pnpm install --frozen-lockfile

  build:
    commands:
      - echo "Deploying $ENVIRONMENT..."
      - ENVIRONMENT=$ENVIRONMENT pnpm --filter=infrastructure run deploy

  post_build:
    commands:
      - |
        CLOUDFRONT_DOMAIN=$(aws ssm get-parameter \
          --name /${PROJECT_NAME}/$ENVIRONMENT/cloudfront-domain \
          --query 'Parameter.Value' --output text)
        echo "✓ Deployed — https://${CLOUDFRONT_DOMAIN}"

cache:
  paths:
    - '.pnpm-store/**/*'
